name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  black-lint:
    name: Black Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run Black
        run: |
          black --check --skip-string-normalization src

      - name: Typing checks
        run: |
          mypy src
