name: Make summary plot

on:
  push:
    paths:
      - 'sa_training.db'

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pandas matplotlib seaborn numpy pyyaml --upgrade pip

    - name: Setup environment
      run: source setup.sh

    - name: Run export script
      run: python scripts/make_summary_plot.py
